# Generated by Django 4.2.16 on 2024-11-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0008_cartitem_user_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
