# Generated by Django 4.2.16 on 2024-11-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0010_alter_orderitem_order_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='deliverd', max_length=20),
        ),
    ]
