# Generated by Django 4.2.16 on 2024-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0014_rename_created_at_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Delivered', max_length=50),
        ),
    ]
